drop table dim_date;
create table dim_date(	
skey                     number(10) primary key, 
the_date                 date, 
day_of_week              varchar2(3), 
day_of_week_full         varchar2(10), 
dayno_of_the_week        number(1), 
weekno_of_the_month      number(1), 
weekno_of_the_year       number(3), 
week_start_date          date, 
week_end_date            date, 
the_month                varchar2(3), 
dayno_of_the_month       varchar2(3), 
month_name               varchar2(3), 
month_name_full          varchar2(10), 
month_start_date         date, 
month_end_date           date, 
the_quater               number(3), 
dayno_of_the_quarter     number(3), 
quarter_start_date       date, 
quarter_end_date         date, 
the_year                 varchar2(5), 
dayno_of_the_year        number(3), 
year_start_date          date, 
year_end_date            date, 
fiscal_day               number(3), 
fiscal_period            varchar2(3), 
fiscal_quarter           number(1), 
fiscal_year_start        varchar2(5), 
fiscal_year_end          varchar2(5), 
fiscal_year_full         varchar2(10), 
fiscal_year_start_date   date, 
fiscal_year_end_date     date, 
leap_year_flag           varchar2(1), 
weekend_indicator        varchar2(1), 
holiday_flag             varchar2(1), 
rec_cr_dt                date, 
rec_up_dt                date);

alter table dim_date add constraint dim_date_ukey unique (the_date);
drop sequence dim_date_seq;
create sequence dim_date_seq start with 1 increment by 1;